metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

metricbeat.modules:
  # Elasticsearch module
  - module: elasticsearch
    xpack.enabled: true
    period: 10s
    hosts: "${ELASTIC_HOSTS}"
    username: "${ELASTIC_USER}"
    password: "${ELASTIC_PASSWORD}"
    ssl:
      enabled: true
      certificate_authorities: ${CA_CERT}

  # Logstash module
  - module: logstash
    xpack.enabled: true
    period: 10s
    hosts: "${LOGSTASH_HOSTS}"

  # Kibana module
  - module: kibana
    metricsets:
      - stats
    period: 10s
    hosts: ${KIBANA_HOSTS}
    username: ${ELASTIC_USER}
    password: ${ELASTIC_PASSWORD}
    xpack.enabled: true
    ssl:
      enabled: true
      certificate_authorities: ${CA_CERT}

  # Docker module
  - module: docker
    metricsets:
      - "container"
      - "cpu"
      - "diskio"
      - "healthcheck"
      - "info"
      - "memory"
      - "network"
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s
    enable: true

processors:
  - add_host_metadata: ~
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: ["${ELASTIC_HOSTS}"]
  username: "${ELASTIC_USER}"
  password: "${ELASTIC_PASSWORD}"
  ssl:
    enabled: true
    certificate_authorities: ${CA_CERT}