packetbeat.interfaces.device: any
packetbeat.interfaces.snaplen: 2000

packetbeat.protocols:
  - type: http
    ports: [80, 8080, 3000, 3001]  # HTTP ports
  - type: tls
    ports: [443]  # HTTPS port
  - type: dns
    ports: [53]  # DNS port
  - type: ssh
    ports: [22]  # SSH port
  - type: ftp
    ports: [21]  # FTP port
  - type: dhcpv4
    ports: [67, 68]  # DHCP ports
  - type: ntp
    ports: [123]  # NTP port
  - type: mongodb
    ports: [27017]  # MongoDB port

output.elasticsearch:
  hosts: ["https://elastic:9200"]
  username: "${ELASTIC_USER}"
  password: "${ELASTIC_PASSWORD}"

setup.kibana:
  host: "http://kibana:5601"

processors:
  - add_cloud_metadata: ~

logging.level: info
