packetbeat.interfaces.device: any

packetbeat.flows:
  timeout: 30s
  period: 10s

packetbeat.protocols:
  - type: http
    ports: [80, 8080, 3000, 3001]  # HTTP ports
    fields:
      service_id: nginx

  - type: tls
    ports: [443]  # HTTPS port

  - type: dns
    ports: [53]  # DNS port
    include_authorities: true
    include_additionals: true

  - type: ssh
    ports: [22]  # SSH port

  - type: ftp
    ports: [21]  # FTP port

  - type: dhcpv4
    ports: [67, 68]  # DHCP ports

output.elasticsearch:
  hosts: ['${ELASTIC_HOSTS}']
  username: "${ELASTIC_USER}"
  password: "${ELASTIC_PASSWORD}"
  ssl:
    enabled: true
    certificate_authorities: ${CA_CERT}

setup.kibana:
  host: "${KIBANA_HOSTS}"
  xpack.enabled: true


processors:
  - add_host_metadata: ~
  - add_docker_metadata: ~

setup.dashboards.enabled: true